### ISSUE TITLE
Private Competition and Registration Link Support

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-web#1]
It would be useful to support private competitions. We can implement this by supporting registration links. These registration links could be used to facilitate registration in private competitions. In the case of something like a classroom settings, the registration link could encode a classroom for the users to automatically join upon registration. This would deprecate the current "classroom joining link."

A simple implementation of this would implicitly encode an **access token** in the link. This would be included upon registration and matched against a document in the DB that codes for action/access.

There should be an administrative interface to manage registration links. You should be able to disable/delete/add but not edit as I can't think of an easy way to migrate users to the updated link.

**Comment by tim-becker** [comment]
This was resolved by PR #22.
