### ISSUE TITLE
Adding / Removing / Redeploying instances

### ISSUE THREAD

**Issue by ethan42** [picoCTF/picoCTF-web#16]
This issue is related to issue #28 on the picoCTF-shell-manager repo. The ability to add a new problem instance, redeploying (or regenerating) an existing one, or removing a (broken) instance are all features we would like to support.

In terms of priority, it seems that removing an existing instance is probably the easiest first step. Once the instance is removed, a different instance will be assigned to all users that had that specific instance. This will allow us to quickly work around broken challenges.

Redeploying/regenerating instances would be next in terms of priority with adding new instances being last.

**Comment by tim-becker** [comment]
Just a status update on this issue. The following things are already implemented and working:
* Redeploying and regenerating specific instances (this is in shell-manager)
* Adding new instances (also in shell-manager)
* _If_ an instance no longer exists in the db, teams that request that instance's data will be assigned to a different instance

The only things we are missing are:
* A clean way to remove instance metadata from the shell server ([issue #13](https://github.com/picoCTF/picoCTF-shell-manager/issues/13) on shell-manager)
* An admin UI element for removing instances from the web server's database. Currently the only way to do this is to manually remove them using the mongo CLI
