### ISSUE TITLE
unit tests are broken

### ISSUE THREAD

**Issue by royragsdale** [picoCTF/picoCTF-web#32]
The removal of create_user_request in 3bd0f77cba8c319d66018208c839d1c47c57504b causes a number of unit tests to break

**Comment by cganas** [comment]
I would suggest holding off on this until #28, though it shouldn't directly affect it may shed light on issues that will again, break the tests.

**Comment by royragsdale** [comment]
#28 was actually my motivation, in the face of a refactoring, I think it would be helpful to have some sort of CI setup to increase visibility into breaking changes as well as an incentive to increase test coverage in any new code.  As an example I have the start of a travis-ci integration on a fork https://travis-ci.org/royragsdale/picoCTF-web.

I planned to update the tests to use create_user. https://github.com/picoCTF/picoCTF-web/blob/master/api/user.py#L156
