### ISSUE TITLE
Order of checking if flag has already been submitted vs. correct

### ISSUE THREAD

**Issue by WilliamParks** [picoCTF/picoCTF-web#45]
I had a challenge where I initially misspecified what the flag was supposed to be. 

I fixed it, and reloaded. However, submitting with the test account got the error that the flag has already been tried. A second test account was able to solve it.

If we have to reload problems mid competition, this could be an issue.

**Comment by cganas** [comment]
Hey! So we have you covered. We currently do not have any sort of web accessible interface for it but there are a suite of functions in problem.py designed to deal with this issue in a more defined way.

https://github.com/picoCTF/picoCTF-web/blob/master/api/problem.py#L504-L589

**Comment by WilliamParks** [comment]
Awesome! Thanks.
