### ISSUE TITLE
Lack of Affiliation Presence

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-web#6]
We currently do not let the user specify an affiliation during registration. Consequently, affiliations are not displayed on the scoreboard. Issue #1 will have to reintroduce the notion of a user/team affiliation. 

However, we still need to support the general case of registering in a public competition with an affiliation.

Resolving this issue would require the contributor to equip the front-page.coffee with the appropriate fields and display the affiliations on the scoreboard.

**Comment by tim-becker** [comment]
This was resolved by PR #22
